GET http://localhost:8090/api/breweries HTTP/1.1
Accept: application/json

###
POST http://localhost:8080/api/breweries HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "location": "Becks",
  "name": "Bremen"
}
